# Generated by Django 4.0.4 on 2022-09-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitionName', models.CharField(max_length=100)),
                ('competitionDescription', models.TextField()),
                ('competitionImage1', models.ImageField(default='dcomp1.jpg', upload_to='competition_pics')),
                ('competitionImage2', models.ImageField(default='dcomp2.jpg', upload_to='competition_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.TextField()),
                ('top', models.CharField(max_length=100)),
                ('left', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=100)),
                ('cityImage', models.ImageField(default='dcity.jpg', upload_to='city_pics')),
                ('cityCompetitions', models.ManyToManyField(to='city.competition')),
                ('position', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='city.position')),
            ],
        ),
    ]
