# Generated by Django 3.2.12 on 2022-09-18 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='left',
        ),
        migrations.RemoveField(
            model_name='position',
            name='top',
        ),
        migrations.AddField(
            model_name='city',
            name='competitionDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='logoLeft',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='position',
            name='logoTop',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='position',
            name='textTop',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='CityComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompetitionName', models.CharField(max_length=100, null=True)),
                ('competitionDate', models.TimeField(null=True)),
                ('competitionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='cityComp',
            field=models.ManyToManyField(blank=True, null=True, to='city.CityComp'),
        ),
    ]
