# Generated by Django 3.2.12 on 2022-09-26 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_remove_position_left_remove_position_top_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='competitionDate',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='CityComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompetitionName', models.CharField(max_length=100, null=True)),
                ('competitionDate', models.TimeField(null=True)),
                ('competitionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='cityComp',
            field=models.ManyToManyField(blank=True, to='city.CityComp'),
        ),
    ]
