# Generated by Django 4.0.5 on 2022-09-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_auto_20220926_1254'),
        ('city', '0003_competition_background_img'),
    ]

    operations = [
    ]
