# Generated by Django 4.0.4 on 2022-09-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_merge_20220926_1846'),
        ('city', '0004_merge_20220926_1859'),
    ]

    operations = [
    ]
