# Generated by Django 4.0.4 on 2022-10-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0007_alter_competition_maximum_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cityCompetitions',
            field=models.ManyToManyField(blank=True, null=True, to='city.competition'),
        ),
    ]
