# Generated by Django 4.0.4 on 2022-10-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0008_alter_city_citycompetitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='rule_booklet',
            field=models.FileField(blank=True, upload_to='competition_pics'),
        ),
    ]
