# Generated by Django 4.0.4 on 2022-10-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0009_competition_rule_booklet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='rule_booklet',
            field=models.FileField(blank=True, upload_to='booklets'),
        ),
    ]
