# Generated by Django 4.0.4 on 2022-10-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0010_alter_competition_rule_booklet'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
