# Generated by Django 3.2.9 on 2022-11-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0012_city_comingsoon'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='completionstatus',
            field=models.BooleanField(default=True),
        ),
    ]
