# Generated by Django 3.2.9 on 2022-11-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0013_city_completionstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='completionstatus',
            field=models.BooleanField(default=False),
        ),
    ]
