# Generated by Django 4.0.4 on 2022-11-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0013_city_scheduleimage'),
        ('city', '0014_alter_city_completionstatus'),
    ]

    operations = [
    ]
