# Generated by Django 3.2.9 on 2022-09-16 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('field', models.CharField(max_length=40, null=True)),
                ('contactno', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=40, null=True)),
                ('solo', models.BooleanField(default=1)),
                ('city', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.city')),
                ('competition', models.ManyToManyField(blank=True, default=None, to='city.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.city')),
                ('competition', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.competition')),
                ('members', models.ManyToManyField(to='users.Person')),
            ],
        ),
    ]
