# Generated by Django 4.0.6 on 2022-09-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Contactno',
            field=models.TextField(max_length=40, null=True),
        ),
    ]
