# Generated by Django 4.0.6 on 2022-09-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_person_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Contactno',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
