# Generated by Django 4.0.6 on 2022-09-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_contactno_person_contactno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_in_a_team',
            field=models.BooleanField(default=0),
        ),
    ]
