# Generated by Django 4.0.6 on 2022-09-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_person_is_in_a_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_in_a_team',
        ),
        migrations.AddField(
            model_name='person',
            name='solo',
            field=models.BooleanField(default=1),
        ),
    ]
