# Generated by Django 4.0.5 on 2022-09-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_person_college_name_alter_person_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='college_name',
            field=models.CharField(blank=True, default='iitg', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='degree',
            field=models.CharField(blank=True, default='btech', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, default='male', max_length=10, null=True),
        ),
    ]
