# Generated by Django 3.2.9 on 2022-09-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_person_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='yearofgraduation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
