# Generated by Django 4.1.1 on 2022-09-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_person_college_name_alter_person_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='countrycode',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
