# Generated by Django 4.0.4 on 2022-10-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_person_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contactno',
            field=models.IntegerField(max_length=40, null=True),
        ),
    ]
