# Generated by Django 4.0.4 on 2022-10-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_person_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contactno',
            field=models.IntegerField(null=True),
        ),
    ]
