# Generated by Django 4.0.5 on 2022-10-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_person_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='college_name',
            field=models.TextField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='countrycode',
            field=models.TextField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='degree',
            field=models.TextField(blank=True, default='B.Tech', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.TextField(blank=True, default='Male', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.TextField(max_length=124),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
