# Generated by Django 3.2.9 on 2022-10-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_person_college_name_alter_person_countrycode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contactno',
            field=models.TextField(null=True),
        ),
    ]
