# Generated by Django 3.2.9 on 2022-10-12 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0011_city_venue'),
        ('users', '0019_alter_person_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.city'),
        ),
    ]
