# Generated by Django 4.1.2 on 2022-11-02 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0012_city_comingsoon'),
        ('users', '0020_alter_person_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='competition',
        ),
        migrations.AddField(
            model_name='person',
            name='competition',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.competition'),
        ),
    ]
